### ISSUE TITLE
undefined local variable or method `getbyte' for TCPSocket

### ISSUE THREAD

**Issue by danabr** [dim/ruby-net-ldap#2]
Running the following code on Windows Vista (32 bit version) results in an error:

```
auth = {:method => :simple, :username => "username", :password => "password"}
ldap = Net::LDAP.new(:host => "my.host.com", :port => 389, :auth => auth, :base => "dc=host,dc=com")

ldap.bind
```

The exception trace looks like this:

```
NameError: undefined local variable or method `getbyte' for #<TCPSocket:0x672cc4c>
C:/InstantRails/ruby/lib/ruby/gems/1.8/gems/net-ldap-0.0.5/lib/net/ber.rb:151:in `read_ber'
C:/InstantRails/ruby/lib/ruby/gems/1.8/gems/net-ldap-0.0.5/lib/net/ldap.rb:1299:in `bind_simple'
C:/InstantRails/ruby/lib/ruby/gems/1.8/gems/net-ldap-0.0.5/lib/net/ldap.rb:1270:in `bind'
C:/InstantRails/ruby/lib/ruby/gems/1.8/gems/net-ldap-0.0.5/lib/net/ldap.rb:754:in `bind'
```

**Comment by s0nspark** [comment]
This is likely caused by the ruby version you're using... I ran into the same error with this lib on 1.8.6 but 1.8.7 runs fine.

**Comment by danabr** [comment]
Yes, at the time I reported it I was using 1.8.6. I switched to 1.8.7 but forgot to report that the problem had been solved.

**Comment by s0nspark** [comment]
:-) I figured you had worked it out by now ... My main aim for commenting
was to help anyone else that might be googling the error.

Cheers,
Tim
